### ISSUE TITLE
How to stop parsing?

### ISSUE THREAD

**Issue by nrikgle** [djspiewak/gll-combinators#27]
Hi, 

Can you please provide some info about it?
If i have a small parser like:

```scala
   def parser: Parser[Int] = a ~ ">" ~ b ^^ { (a, _, b) => 
     // and i stop parser with failure if `a` is equal to `FOO`
  }
```

How to do it?

**Comment by djspiewak** [comment]
Well, there are a couple of things here.  First off, it's important to remember that you should *always* build your context-free grammar in a constructive fashion.  In other words, build a grammar which precisely describes what you *want*, not what you *don't want*.  So rather than saying "I don't want `FOO`", you should say "I want these things".  There are several reasons for this, but conceptually it boils down to the fact that there is an uncountably infinite number of things which are "not `FOO`", and I would not be able to give them all to you.

Second, if you *do* need to negate things, you need to be very specific about what you want to negate.  In general, it is impossible to compute the complement of a context-free grammar (related to the uncountability problem), and so gll-combinators does not provide any such mechanism.  However, it does provide a limited mechanism of negation which works on terminals, similar to the way in which regular expressions provide a negation mechanism.  You can, for example, do something like this:

```scala
  def parser: Parser[Int] = (a \ "FOO") ~ ">" ~ b ^^ { (a, _, b) => 
    // and i stop parser with failure if `a` is equal to `FOO`
  }
```

This would be a parser which parses some text, and if `a` accepts then it checks to see if the text is precisely equal to `FOO`.  If it is, then it rejects.  This form of negation is sound and does not lead to undecidability, and it is quite useful it some cases (like keyword rejection in scannerless language grammars).

Does that answer your question?

**Comment by nrikgle** [comment]
wow, thanks Daniel
